telegram_bot:
  token: ""

restaurant:
  materik:
    site_url: "http://materik.by/"
  vangog:
    instagram:
      url: "https://www.instagram.com/vangoghmogilev/"
      posts_xpath: '//*[@id="react-root"]/section/main/div/div[3]/article/div/div/div/div/a'
      tags_regexp: 'property="instapp:hashtags"\s+content="(бизнесланч|обед)"\s*/?>'
  pizzaroni:
    instagram:
      url: "https://www.instagram.com/cafe_pizzaroni/"
      posts_xpath: '//*[@id="react-root"]/section/main/div/div[3]/article/div/div/div/div/a'
      tags_regexp: 'property="instapp:hashtags"\s+content="(бизнесланч|обед|обеды)"\s*/?>'

database: "./config/lunch.db"
